name: CI
on:
  push:
    # this workflow is triggered on every:
    branches:
      - "**"    # push to a branch
    tags:
      - "v*"    # and on pushes that create tags matching the patterin `v*` (e.g., `v.1.0`).

jobs:
  build: # job 1 - build
    name: Package Extension
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Setup Node.js environment 
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      # Install dependencies
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          npm install
          npm install --global @vscode/vsce
          sh ./package.sh
      - name: Upload extension
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./dist/*


  publish: # job 2 - publish
    runs-on: ubuntu-latest
    needs: build
    # This job runs only if the build job is successful and the push is to a tag
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      # Download artifacts produced by the build job using actions/download-artifact@v2.
      - uses: actions/download-artifact@v2
      #  finds the .vsix package and publishes it
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          # The VSCE_PAT (Visual Studio Code Extensions Personal Access Token) is used for authentication.
          VSCE_PAT: ${{ secrets.VSCE_PAT }}